project:
  type: website

website:
  title: "PvSeroApp: A Sero-Surveillance Tool"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: theapp.qmd
        text: The App

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
